import json
import uuid
from datetime import datetime
from typing import Annotated, Any

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field, model_validator


def parse_topics(v: Any) -> list[str]:
    """Ensure grammar topics are deserialized into a list of strings."""
    if isinstance(v, str):
        try:
            parsed = json.loads(v)
            if isinstance(parsed, list):
                return [str(i) for i in parsed]
        except Exception:
            return [v]
    elif isinstance(v, list):
        return [str(i) for i in v]
    return []


class LatinExample(BaseModel):
    """A contextual Latin sentence example with translation and grammar breakdown."""

    latin: str = Field(description="Exemplo de frase em Latim clássico")
    translation: str = Field(description="Tradução fiel para o Português")
    grammatical_notes: str = Field(
        description="Notas explicativas sobre a sintaxe, casos e desinências"
    )


class VocabularyItem(BaseModel):
    """A vocabulary item introduced in the lesson."""

    word: str = Field(description="Lema da palavra em Latim")
    dictionary_entry: str = Field(
        description="Entrada lexicográfica canônica (ex: 'puella, -ae, f.')"
    )
    grammatical_class: str = Field(
        description="Classificação morfológica (ex: 'Substantivo feminino de 1ª declinação')"
    )
    translation: str = Field(description="Tradução em Português")
    example_sentence: str = Field(description="Frase curta exemplificando o uso")


class LessonExercise(BaseModel):
    """An interactive Latin exercise with pedagogical feedback."""

    id: int = Field(description="Identificador numérico do exercício")
    exercise_type: str = Field(
        description="Tipo de exercício: 'multiple_choice', 'fill_blank' ou 'translation'"
    )
    instruction: str = Field(description="Instrução do exercício para o aluno")
    question: str = Field(description="Pergunta ou frase a ser resolvida")
    options: list[str] | None = Field(
        default=None,
        description="Alternativas no caso de questões de múltipla escolha",
    )
    correct_answer: str = Field(description="Resposta exata esperada")
    explanation: str = Field(
        description="Explicação gramatical completa justificando a resposta correta"
    )


class TheorySection(BaseModel):
    """A focused theoretical explanation of a grammatical point."""

    topic: str = Field(description="Título do tópico gramatical")
    explanation: str = Field(description="Explicação didática detalhada")
    rule_summary: str = Field(description="Resumo da regra ou tabela mnemônica")


class HistoricalTrivia(BaseModel):
    """An authentic historical or archaeological curiosity contextual to the lesson."""

    title: str = Field(description="Título instigante da curiosidade romana")
    fact: str = Field(description="Fato histórico, cultural ou arqueológico autêntico")
    content: str | None = Field(
        default=None,
        description="Alias de conteúdo para compatibilidade com o frontend",
    )
    latin_motto_or_phrase: str = Field(
        default="",
        description="Lema latino ou expressão autêntica associada ao fato",
    )
    century_or_period: str | None = Field(
        default=None,
        description="Século ou período histórico associado",
    )
    source_reference: str = Field(
        description="Fonte historiográfica ou arqueológica (ex: Plínio, Pompeia, Tito Lívio)",
    )

    @model_validator(mode="after")
    def sync_content(self) -> "HistoricalTrivia":
        if not self.content and self.fact:
            self.content = self.fact
        elif not self.fact and self.content:
            self.fact = self.content
        return self


class LessonContent(BaseModel):
    """Complete structured lesson content generated by the AI Professor Agent."""

    lesson_id: str
    module_title: str
    lesson_title: str
    pedagogical_goal: str
    historical_context: str
    theory_sections: list[TheorySection]
    examples: list[LatinExample]
    vocabulary: list[VocabularyItem]
    exercises: list[LessonExercise]
    teacher_tip: str
    historical_trivia: list[HistoricalTrivia] = Field(
        default_factory=list,
        description="Curiosidades culturais e históricas romanas vinculadas à aula",
    )


class LessonCompleteRequest(BaseModel):
    """Payload to mark a lesson as completed with score."""

    score: int = Field(default=100, ge=0, le=100, description="Nota de 0 a 100%")


class LessonSummaryResponse(BaseModel):
    """Compact summary of a lesson."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    module_id: uuid.UUID
    order_index: int
    title: str
    pedagogical_objective: str
    grammar_topics: Annotated[list[str], BeforeValidator(parse_topics)] = []
    is_completed: bool = False


class CourseModuleResponse(BaseModel):
    """Course module with nested lessons for navigation."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    order_index: int
    title: str
    description: str
    level: str
    lessons: list[LessonSummaryResponse]


class LessonProgressResponse(BaseModel):
    """Current learning stage and stats of the student."""

    user_id: uuid.UUID
    current_module_id: uuid.UUID | None
    current_lesson_id: uuid.UUID | None
    current_module_title: str | None
    current_lesson_title: str | None
    completed_lessons_count: int
    total_points: int
    current_streak_days: int


class CompletedLessonSummary(BaseModel):
    """Historical record of a completed lesson for the Tabularium."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    completion_id: uuid.UUID
    order_index: int
    title: str
    module_id: uuid.UUID
    module_title: str
    score: int
    completed_at: datetime
    pedagogical_objective: str
    grammar_topics: Annotated[list[str], BeforeValidator(parse_topics)] = []
